version: '3.1'
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - some-net
  javaDA:
      image: demo_animals
      depends_on:
         - db
      restart: always
      environment:
         - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
         - SPRING_DATASOURCE_USERNAME=postgres
         - SPRING_DATASOURCE_PASSWORD=postgres
      ports:
         - "8075:8075"
      build:
         context: ./java
         dockerfile: Dockerfile
      networks:
         - some-net
networks:
  some-net:
    driver: bridge